export const favorites = [
  {restaurant: 'Even Stevens'},
  {restaurant: 'Del Taco'},
  {restaurant: 'Jinya Ramen'},
  {restaurant: 'Jimmy John’s'},
  {restaurant: 'Toro Taco'},
  {restaurant: 'Chik-Fil-A'},
  {restaurant: 'Mo Bettah’s'},
  {restaurant: 'Costco'},
  {restaurant: 'Tandoor'},
  {restaurant: 'Chicken Express'},
  {restaurant: 'DP Cheesesteaks'},
  {restaurant: 'Wendy’s'},
  {restaurant: 'New Golden Dragon'},
  {restaurant: 'In-N-Out'},
  {restaurant: 'Cafe Zupas'},
  {restaurant: 'Noodles and Company'},
  {restaurant: 'Dickies'},
  {restaurant: 'R&R Barbecue'},
  {restaurant: 'Moochie’s Meatballs'},
  {restaurant: 'Rancheritos'},
  {restaurant: 'El Pollo Loco'},
  {restaurant: 'McDonalds'},
  {restaurant: 'Grove Market'},
  {restaurant: 'Victors Tacos & Tires'},
  {restaurant: 'Thai Food'},
  {restaurant: 'Cup Bob'},
  {restaurant: 'Greek Place'},
  {restaurant: 'Spitz'},
  {restaurant: 'Taco Stand'},
  {restaurant: 'Town & Country Market'},
]